import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import Link from 'next/link';
import Image from 'next/image';

import logo from '../public/logo.png';
import Menu from '../components/menu';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`h-screen flex`}>
        {/* LEFT */}

        <div className='w-1/6 md:w-[8%] lg:w-[16%] xl:w-[14%]  bg-red-500 p-4'>
          <Link
            href='/'
            className='flex items-center justify-center lg:justify-start gap-2'
          >
            {' '}
            <Image src={logo} width={32} height={32} alt='logo' />
            <span className='hidden lg:block'>schl. mgt.</span>
          </Link>

          <Menu />
        </div>

        {/* RIGHT */}
        <div className='w-5/6 md:w-[92%]  lg:w-[84%] xl:w-[86%] bg-blue-200'>
          r
        </div>
      </body>
    </html>
  );
}
